# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package with React Build

on:
  release:
    types: [created]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    # Set up JDK for Spring Boot backend
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}
        cache: maven
    
    # Set up Node.js for React frontend
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: FRONTEND/package-lock.json
    
    # Install frontend dependencies and build React app
    - name: Build React frontend
      run: |
        cd FRONTEND
        npm ci
        npm run build
        mkdir -p ../BACKEND/src/main/resources/static
        cp -r build/* ../BACKEND/src/main/resources/static/
      continue-on-error: false
    
    # Cache React build output
    - name: Cache React build
      uses: actions/cache@v3
      with:
        path: FRONTEND/build
        key: ${{ runner.os }}-react-build-${{ hashFiles('FRONTEND/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-react-build-
    
    # Run tests for backend
    - name: Test with Maven
      run: mvn -B test --file BACKEND/pom.xml
      continue-on-error: false
    
    # Package the application
    - name: Build with Maven
      run: mvn -B package --file BACKEND/pom.xml -DskipTests
      continue-on-error: false
    
    # Update pom.xml with GitHub Packages configuration
    - name: Update pom.xml for GitHub Packages
      run: |
        cp BACKEND/pom.xml BACKEND/pom.xml.bak
        if ! grep -q "<distributionManagement>" BACKEND/pom.xml; then
          sed -i '/<\/properties>/a \
          \    <!-- GitHub Packages Distribution Management --> \
          \    <distributionManagement> \
          \        <repository> \
          \            <id>github</id> \
          \            <name>GitHub Packages</name> \
          \            <url>https://maven.pkg.github.com/${{ github.repository }}</url> \
          \        </repository> \
          \    </distributionManagement>' BACKEND/pom.xml
        fi
      continue-on-error: false
    
    # Publish to GitHub Packages
    - name: Publish to GitHub Packages
      if: github.event_name == 'release'
      run: mvn deploy -s ${{ github.workspace }}/settings.xml -f BACKEND/pom.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
      continue-on-error: false
    
    # Cleanup step
    - name: Cleanup
      if: always()
      run: |
        if [ -f BACKEND/pom.xml.bak ]; then
          rm BACKEND/pom.xml.bak
        fi
